"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Set site hostname
BASE_URL = 'http://127.0.0.1:8000'

LOGIN_URL = '/auth/login'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!a8^@i#q$sa8ox)qcc+_r&7a+zt=iohy6vh5#augc*0^@*cmvn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# media
MEDIA_ROOT = f'{BASE_DIR}/media'
MEDIA_URL = '/media/'


ALLOWED_HOSTS = []

LANGUAGE_CODE = 'ru'


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_results',

    'main',
    'authentication',
    'cart',
    'shop',
    'order',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.context_processors.category_list',
            ],
        },
    },
]


STATICFILES_DIRS = [
    BASE_DIR / "static",
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}
# Redis settings
REDIS_DATABASE = {
    'HOSTNAME': 'localhost',
    'PORT': 6379,
}

# Change standart auth model
AUTH_USER_MODEL = 'authentication.User'


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

TIME_ZONE = 'Europe/Moscow'
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session name for cart
CART_SESSION_ID = 'cart'

# Session name for code_confirm
CODE_CONFIRM_SESSION_ID = 'code_confirm'

# Enable number formatting with thousand separators
USE_THOUSAND_SEPARATOR = True

# Mailing paramerts
EMAIL_HOST = os.getenv('MAILING_SMTP_SEVER')
EMAIL_PORT = os.getenv('MAILING_SMTP_PORT')
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = os.getenv('MAILING_EMAIL')
EMAIL_HOST_PASSWORD = os.getenv('MAILING_PASSWORD')

# Qiwi pay parameters
QIWI_SECRET_KEY = os.getenv('QIWI_SECRET_KEY')
BILL_ID_LENGTH = 30

# Shop settings
PAGE_PRODUCTS_COUNT = [12, 24, 36]
ORDER_ICONS = {
    'up': {'icon': '↑', 'value': 'up'},
    'down': {'icon': '↓', 'value': 'down'},
}

PRICE_MULTIPLIER = 1.1
