# Generated by Django 4.1.6 on 2023-02-08 19:51

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=32, verbose_name='Имя категории')),
                ('cat_slug', models.CharField(max_length=32, verbose_name='URL параметр')),
                ('type', models.CharField(max_length=32, verbose_name='Тип (нужен для парсера)')),
                ('url_slug', models.CharField(max_length=128, verbose_name='URL параметр магазина')),
                ('site_name', models.CharField(choices=[('dns', 'DNS'), ('biggeek', 'BIGGEEK')], max_length=32)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Настройки парсера',
                'verbose_name_plural': 'Настройки парсера',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=main.models.Slider.get_file_path, verbose_name='Фото слайдера')),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер',
            },
        ),
        migrations.CreateModel(
            name='IndexCats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Категории', max_length=120, unique=True)),
                ('left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_left', to='shop.category', verbose_name='Категория слева')),
                ('right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_right', to='shop.category', verbose_name='Категория справа')),
            ],
            options={
                'verbose_name': 'Категории на главной странице',
                'verbose_name_plural': 'Категории на главной странице',
            },
        ),
    ]
