# Generated by Django 4.1.6 on 2023-02-08 19:54

from django.db import migrations, transaction
from django.core.files import File
from random import randint


def _open_file(name: str) -> File:
    return File(open(f'static/filling_db/{name}', mode='rb'), name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    def fill_cats_breed(apps, schema_editor):
        index_cats = apps.get_model("main", "IndexCats")
        cats = apps.get_model("shop", "Category")
        product = apps.get_model("shop", "Product")
        with transaction.atomic():
            cat_obj = cats.objects.create(name='Разное',
                                          photo=_open_file('other.webp'),
                                          slug='other')
            article = randint(100, 999)
            product.objects.create(
                    vendor_code=article,
                    name='Тест оплаты',
                    photo=_open_file('test.webp'),
                    description='Тест оплаты на сайте',
                    category=cat_obj,
                    price=1,
            )

            product.objects.create(
                    vendor_code=article+1,
                    name='Кошке на корм',
                    photo=_open_file('cat.webp'),
                    description='Соше на пакетик корма',
                    category=cat_obj,
                    price=10,
            )

            index_cats.objects.create(left=cat_obj, right=cat_obj)

    def delete_cats_breed(apps, schema_editor):
        pass

    operations = [migrations.RunPython(fill_cats_breed,
                                       reverse_code=delete_cats_breed)]
