# Generated by Django 4.1.6 on 2023-02-27 20:34

from django.db import migrations, transaction


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230208_2254'),
    ]

    def fill_parser_settings(apps, schema_editor):
        parser = apps.get_model("main", "Parser")

        with transaction.atomic():
            parser.objects.create(cat_name='Фотоаппараты',
                                  cat_slug='fotoapparaty',
                                  type='photo',
                                  url_slug='/catalog/17a89d2b16404e77/zerkalnye-fotoapparaty/',
                                  site_name='dns')

            parser.objects.create(cat_name='Умные колонки',
                                  cat_slug='speakers',
                                  type='smartspeaker',
                                  url_slug='/catalog/17a8c3d816404e77/portativnye-kolonki-i-audiosistemy/?order=6',
                                  site_name='dns')

            parser.objects.create(cat_name='Apple iPhone',
                                  cat_slug='apple-phone',
                                  type='phone',
                                  url_slug='/catalog/apple-iphone',
                                  site_name='biggeek')

            parser.objects.create(cat_name='Xiaomi',
                                  cat_slug='xiaomi',
                                  type='phone',
                                  url_slug='/catalog/cmartfony-xiaomi',
                                  site_name='biggeek')

            parser.objects.create(cat_name='MacBooks',
                                  cat_slug='macbooks',
                                  type='mac',
                                  url_slug='/catalog/noutbuki-apple',
                                  site_name='biggeek')

            parser.objects.create(cat_name='Игровые приставки',
                                  cat_slug='consoles',
                                  type='consoles',
                                  url_slug='/catalog/igrovie-pristavki',
                                  site_name='biggeek')

    operations = [migrations.RunPython(fill_parser_settings)]
